### ISSUE TITLE
Security panel Policies - All

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1297]
**Describe the bug**
This really is not All as it does not show all.  It is really a summary.  Also the individual items maybe need more detail - Execute what?, Update what?, Delete what?  They have lost their context having been listed here.

**To Reproduce**
1. Go to Security panel
2. Click on collection
3. Click on user
4. See issue

**Expected behavior**
I would be in favor of just removing this item and forcing users to select from the dropdown.  Maybe have it called "Select" and then list the options or choose one as the default to show first.

**Screenshots**
![Policies](https://user-images.githubusercontent.com/7501989/164328044-17cbfcd1-be01-4d7e-b1fa-f8c60f11f4e4.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed by hiding the policy lines when user is super admin

**Comment by grantfitzsimmons** [comment]
I think Andy was saying that this list should communicate better what each option gives the user

![image](https://user-images.githubusercontent.com/37256050/166984106-03cbcec8-2c9d-4a1c-b0f4-ec5fed7b67e8.png)

I can still see the policies under a super admin account on the super admin (abentley) and all other users
