### ISSUE TITLE
Loan preparations cannot be associated with existing loans

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2565]
> I created an empty loan and then tried to add the preparations via the loanpreparation table in workbench

![image](https://user-images.githubusercontent.com/37256050/206487498-fb947e2b-cb0e-439c-abe3-df4749771a40.png)

---

A more in-depth look at another instance of this issue:

> I've added the spreadsheet I used for the workbench upload with a screenshot of the mapping. The collection objects all have one preparation but the "Dan-test124" loan already exists. We'll have hundreds of preps to add to a loan at a time (even though this example just has the one row) - can you spot any differences in the setup from your testing?

![image](https://user-images.githubusercontent.com/37256050/206487561-4b6012c1-d62f-47a3-a9b3-b86490ac2d4c.png)

![image](https://user-images.githubusercontent.com/37256050/206487587-8259236f-0d35-48ee-9887-f003b7d48194.png)

![image](https://user-images.githubusercontent.com/37256050/206487697-0c8995d2-ee4d-4d54-9628-022de0a159df.png)

[testing loanprep workbench - Copy.xlsx](https://github.com/specify/specify7/files/10186869/testing.loanprep.workbench.-.Copy.xlsx)

**Comment by grantfitzsimmons** [comment]
It matches an existing loan exactly– no trailing whitespace

**Comment by grantfitzsimmons** [comment]
https://sp7demofish.specifycloud.org/specify/workbench/3/

Recreated it just now- see for yourself!

Existing loan: https://sp7demofish.specifycloud.org/specify/view/loan/251/

**Comment by maxxxxxdlp** [comment]
Looks like it wants to create new records:

![Screenshot 2022-12-08 at 12 49 37](https://user-images.githubusercontent.com/40512816/206541597-a715af60-1784-4253-a346-cff58adfb074.png)

Must match:
![Screenshot 2022-12-08 at 12 58 24](https://user-images.githubusercontent.com/40512816/206543491-efc8393f-0d20-47b8-860f-6c717533e94b.png)

**Comment by maxxxxxdlp** [comment]
Need to debug why back-end wants to create new loans rather than match existing

**Comment by grantfitzsimmons** [comment]
From @chanulee1:

> Can add loan preparations to an existing loan but going to preparations show that they are not loaned. Happens when adding with both catalog numbers and records sets. Also, adding preparations does not trigger the save button. (Edit: Appears to be duplicate of #2565)
> 
> https://user-images.githubusercontent.com/103299204/215572840-c43d6698-77dd-4fd8-ab3f-70e3afe23459.mp4
> 
> https://coldfish-edge.test.specifysystems.org/specify/view/loan/325/
>

**Comment by realVinayak** [comment]
Happens because loan, for some weird reason, has both discipline and division. Specify seems to only set discipline, but workbench looks at both (but discipline happens to be null, so it doesn't match). Don't know why it was done that way. I can look at the lowest not null scope, and ignore everything above (if discipline is a match, division is guaranteed to be same). that should fix this

**Comment by grantfitzsimmons** [comment]
Mentioned again by CSIRO in [#620 on BoldDesk](https://specifysoftware.bolddesk.com/agent/tickets/620):
> We're onboarding our algae collection who will be doing a lot of Gift interactions, often with multiple linked preparations. We really would like the ability to amend existing loans with additional linked preps. This is the case for our Herbarium instance as well, where they often have hundreds of linked preps.
> Will be even more pertinent in light of recent enhancement that allows direct linkage through something like the prep barcode field.
> 
> To get around this at the moment, we create the loan and all the linked preps at the same time through a Loan Preparation workbench. However, limitation is that you then cannot use auto-numbering, as the Loan Prep workbench needs a loan number to link all the preps together to the same interaction. This means users have to go and find what the next loan number should be, and enter it into the workbench. Gets even trickier (as with our insect collection) when there are multiple users uploading loan prep workbenches - they might not get the next number correctly.

**Comment by zoewarner1** [comment]
Hi @grantfitzsimmons - just noting with our testing of v7.21.0.6-csiro, that we can now add additional Loan Preparations to an existing loan through a workbench Loan Prep upload, BUT only if we are linking via a Preparation identifier. If we link via Collection Object catalogNumber and Prep Type, we still get the error noted in this ticket.

Error when trying to upload via Collection Object catalogNumber and Prep Type - error, upload wants new unique loan number

<img width="1627" height="197" alt="Image" src="https://github.com/user-attachments/assets/47b920dc-5099-4f23-98aa-814082a34d31" />



No error - successful upload of three additional preps to existing loan - using Preparation identifier PrepNo (note the workbench did warn me I needed to add Collection Object catalogNumber and PrepType to the mapper, but I ignored it and was able to continue and upload successfully)

<img width="1574" height="189" alt="Image" src="https://github.com/user-attachments/assets/aaf5b485-f315-41a1-abf2-4fa936cf6b17" />
