### ISSUE TITLE
Error with deletion blockers

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3576]
Error recieved when trying to delete Agent record. This is after deleting the prohibitive Collector record. 

**To Reproduce**
1. Go to Agent form
2. Click on Delete
3. Click on Collector Record button to delete record blocking initial deletion
4. Click delete again on Agent record
5. See error

**Expected behavior**
Should allow for deletion of agent file 

**Screenshots**

https://github.com/specify/specify7/assets/135047322/840c0a66-e350-4f17-b03a-4a4db5e1a731
[Specify 7 Crash Report - 2023-06-05T16_01_07.765Z.txt](https://github.com/specify/specify7/files/11654818/Specify.7.Crash.Report.-.2023-06-05T16_01_07.765Z.txt)

**Desktop:**
 - OS: Mac Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.8.12

**Database Name:**
KU Fish Observation

**Comment by bronwyncombs** [comment]
https://github.com/specify/specify7/assets/135047322/d379d15a-8515-4fdf-aaba-b2161f4e7d5b

Also occurs with Collection Information records, but without an error message. 

https://kuvertpaleo11123-v7812-prerelease.test.specifysystems.org/specify/view/collectingevent/134251/

**Comment by melton-jason** [comment]
It looks like there is a separate issue happening in each video. 

In the first video (with Agent), the Agent is actually referenced as a Collector in three more Collecting Events!
However, the deletion blockers only display one of the Collectors. 
Thus, you _do_ delete the Collector, and the form thinks there is nothing left blocking deletion.  
However, when you go to delete the Agent, the backend notices there are three more Collecting Events using the Agent as a Collector and throws the exception. 
This issue has been in Specify for a while now! At least in Specify 7.8.9! (I did not check earlier versions, but it probably was a bug as well). 
@grantfitzsimmons this bug is fixed in `xml-editor`. How pressing do you think this issue is? Can we wait for the `xml-editor` release? If not, I can (probably) pretty much copy/paste the code, but this might make merge conflicts more confusing to resolve when `xml-editor` is being merged into production. 
(Please share your thoughts @bronwyncombs if you have any!)

Regarding the second video, the Collecting Event _is_ deleted through the dialog, but you should definitely be navigated to the home page and the dialog be closed. 
The issue here is that Collection Object is a deletion blocker of the Collecting Event. 
In this instance's setup, a Collecting Event is automatically created when a Collection Object is created. When its Collection Object is deleted, it also deletes the Collecting Event (if "attached"). 
Thus when you delete the Collection Object through the deletion blocked dialog, the Collecting Event you were just viewing gets deleted as well. 
I'm not sure _why_ the Collecting Event getting deleted via the Collection Object deletion causes the behavior as shown in the video, but I'll take a look!

**Comment by bronwyncombs** [comment]
https://github.com/specify/specify7/assets/135047322/a7a978d5-6861-424e-9d6f-1f8cfeca9345
Found this issue again with deleting collecting information through taxon

**Comment by bronwyncombs** [comment]
From Accession forms-- When trying to delete I'm prompted to delete CO, also triggering the error. 

<img width="1440" alt="Screen Shot 2023-06-08 at 11 05 55 AM" src="https://github.com/specify/specify7/assets/135047322/1c93a84e-543f-4d4a-aa8a-318e39e417af">

https://github.com/specify/specify7/assets/135047322/b16d0feb-a26e-4210-9467-e978a23365e5

I am able to delete Collection Object records with Accession numbers, Taxon, Locality etc. attached from the CO form 

https://github.com/specify/specify7/assets/135047322/d93ec9da-b80b-47e7-bb68-5ad5b15bfb8d

**Comment by grantfitzsimmons** [comment]
> this bug is fixed in `xml-editor`. How pressing do you think this issue is? Can we wait for the `xml-editor` release? If not, I can (probably) pretty much copy/paste the code, but this might make merge conflicts more confusing to resolve when `xml-editor` is being merged into production.

I don't think this is that pressing as it has been around for a long time. Since we have a fix for this, let's prioritize getting bug fixes on that branch. If we are still not close to release a month from now, we should copy that fix over as an independent PR.
